language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: aninotes
  api_key:
    secure: NKbLzHPjGWRM5qRnhFPY1TcgybIyr/WX0lZDLNfFf0Tdg1zS/K8snx0tvaHcgEYs/zatH0YhV1bhtcQYmmxoo7U7SlDShOD/js1duKRwjrSf2B/mb7ig5JX4kRDkEqRAPnACUfdkl5ZQBIq+jACQWNKm15Cikf6hlD72TwjYNffprD7CPhLnxESCAQ3E1wlBUpcruCMZ2QqPl92vwhlz7sKT+Uc9qdgUHklsxJ4nQ01OufGmnmsGG1A+1kjR1QsKKXZJOAI2LcdYFHbm/HMn+duFkQjfkT/oRP+OCHRSH+TocjRuBsmlCxtzHqJOzlKvBogiJOz2YY/ItrfGTrY5/FbAcxpcmFeLuPqnPuNLmH5ZRFZZoxiGN4YZsfJVojdNo7yu4VvTP/huBGhTR6syNQJslFlQ8fhVO/EGK92n11EGEIIaY/n7ii/qBchQZIK9vo6iukCtwPsWjP9FmfoDXCQhTJ442y6EIGjNb6AOwKudfmBC9l1s7GeaBr1ouy0la8spsZfUjqDajQQyryj00DGNng54zH/buDy+JzVseQ0OurtgRGN0TmFO1bndj52ejDLZqBPDI+mrOjKrtU9HpREKICeK34PeDKlUxptMhilbIt5fTi8aHbwVYeuJ86T+FOsQ29/XmgM8nNrpibR6EzNrLxh9KqwhWqQGxOcwTcM=
