language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: aninotes
  api_key:
    secure: DHW6qC34uVFmxHS/TC4Axw2phj2/oElyxA+arwKBQxcLk28UbZF2JLmX9IFODoSlg2e/IRQwE6J0JW7ZWngDZhLd67pNH4Si5cngMB4E6JgZ8YnGzZKrh1C0qQ7xx80qL/od5A1qAXvKaYVIkRif45JPDF54kRbK74H3RFaA2ZPw2V2KBjLNRJ8x/RsJuClkNhoYPkwxgTAh9z5iVYyvyaTd6ZZZGNI1FJVhnoS3/gpLF3sVi0g38oz+qRDaaxnu0am63Tm9bkdPIkSS6kZ/8q1I0R3/NEpcOEZg6eB6fYyxj2mxpf0Wqk85rKhU1bxKhZTZGKwWegMBIgW1l0ZKhuaEg8qtT4yJd7SD1RXGQuMXt3iqImsNLeVqQqzP7Mp7UuvmPP8MGOnR5New7WKtW7PN3JE150Txadk8DMLLclpNFeVJAubWU52MbQXaU4+5knnlFlfNtpXDDMACNVYJSUMlRcGkUcluspJ7/TebiAfyBmmt6vLscUaw5/7YLE9mwqveFRgJfXKW/QxcmEkuJ0+vXvdj+uirM86txzwRiZDQ49PWBXG3/CoRuGALs4Gn/6suve+/HlJgCMnNAjOEGMpWk1bSsXADI8nqfhHemezF1f4wH00+H72jhWOry7AZpUC0zZY7S8TAkpVGZQWJ+x8MNt5fNeSteMYMoIYr1Ic=
