language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: aninotes
  api_key:
    secure: h1NUsOxvV8mMkaaYH5V+yNcBqdjYv7+b17D0TTmuzYEZREaqBywtduYvUHJtI1QXgkIkSQtMOfezUEFmjzg3vrt/zMOyX/ESuYBADeVgOxffR8eApoqFIV/tLzMNx4GROJoTcpp6UUtFitBzZwYk4On/8W9DyJo54JB68lEDvV+9+zudqhWAzW6jP9reHUbrjBvUkvl/jl32pg2X4KJtxsYEPzZCGgLmqgXxVPEn5Fguu0psqxXxHhBxyzoVeE0seFquDqbhZS0N0AuNd0JvJRASh6numEuFAbXlAWR28T2U+ZLJ6uuF2mXHg28nHriHZ35kx3fFwKe1b6oCN99qGLD9moSvIIq+6XCklIBKmsWGcWc70nWha26JR11lyF0b6JASMbOvKO3BFnbfX5Bsoyn7nzyFr5F8CJLta9yZj0cnW07i4/YsyWTdm2gOfE7Cl1E9hY90iKYSJv5hzfnikJ0k/He5KrIx2rHUvDhGDJ7CIQehmxWng3LlThiXDSKg8BUs75QYro4pF2OHZx1tknk+qb+mbOcG5hpnjKcyuip+DjNdb5AV+W8lAUbRZjbCeMNAGpF1MPTTYG2alUW/UCCcwkI5cVMeehq/dJyRG4JHbfDLPDktnvm2mfIH/CIqkGlvMwS7TzmRQao4P0avX1MpNGQkhypg90Gh5Qu6ww4=
