language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: aninotes
  api_key:
    secure: Laj7jr96dYPFyqhyE9s3fIPUU+K+Io1vUMXzrMdy3V4h0+OwOQJTzrqPIm/ZJ/zQDqJ3JtnQ3nQjtrVQ381tscveMZfKmKr5dvOsf03PWRhIZuDe2XIE7Pb7FC4+/xzWjGmSfH+ITmxzERTZgNVdLU6//NOs1cjhYXnKRE3DnS0EJZhV1upz6qQyZyWjJNEZq7aTQnBiThB8JbRKvoJSBL/Ouy6q0UhoV2FtfUywkIEHWxY5nzh2HIkgodnniDb5XaSt2WEJx85TawXKv9AAUgP8hfBQ9IOW1evhr9PEYwM3QR4jZF5RZX2VVn+fDj8LjH8nQzSLu3CoEiq1GUHVYd5zUJjr2YT8ASonCkQ1lxbIHQUrmDl5KgTc+MJphCufU7LIUg/YujocfBSdV9Jw3OKiCnKz/5zo+o4xF46nAHNVYFGn39AXgOlksLwLAcsow4RNVEkIUeslRnT6lDsPmZKZbXQJdyFFxbJD6+Qq4OoMDewuojfyemBv1NakOrp+FQ7nCi5knbnW8gtJc0ksb7a2duxrf1faBjZCqmxHvhEsp//Ey/T0jGuiPNauhvUGNX2cRqy1vvaRaaZiruBKfEOKun31vo71FTQDanqvcc/g1LE/i71Nb1ka+ctpEIg3qxTO9khIiHPCAnVe8147MYk7YI3FIBbz+L7NBm2XUzY=
