language: node_js
node_js:
  - '10'
before_install:
  - npm install -g @angular/cli
install: npm install
branches:
  only:
    - master
deploy:
  provider: heroku
  app: aninotes
  api_key:
    secure: ATS/t/L6+Mfr7eEfoNyLQ/4THozz8CdrMZ3F6VSaVUHcQmBRwzLrcvoXkw0JG3/jRI8cXzJ0Ds7BpbOmXuytN3+za7ZWIqaNb++kjyjJu7tYBZqxQUz+7nyPt7BtMeBb3oAs7OLeC7yi8DDnFNAS/wMsAr7M3klcE4uwdShRoZaPvtjBfW9stdcSjE4LjpE7q5AXHNnkhPYEhIG1PU+G13pGkz9E60Xa567kUk74gyHMVQ/nc4i17ans/zTsfnlMRMC6EVJw65p+yLAAeu1yNhr7mVlLfq3cYzkDHyQSejdJ4D3TuVXGaAlnHnta0U57BgqKouGFmjRW3nkU4rAP6WsrNwZJyvLQqgw/AfDUsAZfLzpxaTFgHCtPFUdW2tGA82wzu1CN0L0yABef5gYv6FaLXRMH4UW9xQCUaQV9wG4BJR5XEeSlLmvUBCi5zEn0jYdbXXFClE+fTEr/g7dOes5D9o5mFYcJbPtqwEQ8GOdaaQcKCdyOhERMeSL9IZkDsiUm78EjA+aYOp1Zka/rQi71YAPSBCtdjahtSlqdjn3FxqLjNeShVpuyQPDCE70309BLlkER3AiEAwZqtvFnaZGYjPyqgLDxi8zbagXcFsnml9kZeSj7cwAUkYUJSSXocSioUvFJ8rrtrndVRCnBqkqKyVTJal1yF+JcAvkVboQ=
