language: node_js
node_js:
  - '10'
before_install:
  - npm install -g @angular/cli
install: npm install
branches:
  only:
    - master
sudo: required
deploy:
  provider: heroku
  app: aninotes
  api_key:
    secure: QlWM1XLz1FJ2twcKx+9LUGRW4wVaKpdBVQvfm5OSVUCyUY0j10pi7JT+Q/wmDPMkXFjcoGadWnZ208CpaTMYcSfEakcu3xEJeBeq4a6UHgkvpdyDaRaGcVTDKK/45ZZNl/vvkvZQOaVgkwSDagxPbVEL24r7L7a4EntKEkVivq17S1be+NxJfEYuhtiGf5XhqWISwbXqdGi71sBtxu/tKEtJB3Ssw5mN5K5Mq73qkE/b+WvOryTUQIH2oXn8dhGZnBBn8aiQm6p+bijbsO0xiWzWy58YQwlp5uVbHHhiumfNhpN2WY57303KOm02lwxRSTnGfWhcRs8Q2By+oFLPHjUR6BMU/pRSszhaz3W8ypv7ChRruGM4A4eQ71AB+ixHjRPPvZp4MEI/sFTOEZnruwC3Kv7JSxtNv9TGf9AnqAyUtYCRGVvllrNQm8u/SQJqxKFkJ3PN4pnP9UpZUlEUfV5gXq9YvxYOoPGc5Die/VxR2wEMbYkh3KxnqkaOmc95RA38NnVNWe5KPKGDoMaBEWi5CSHvj5kZXHr+R1uCSj7VP2lu/07rjO84kOs8SvivK0zXYabLrWGG0cMUxFl6XX2duTJTSr1Ke24yhFVpJ0bE56ouvD/M9Qbqw22SuApwMrw1W9tAf1Fy5vm8WPPk+onlbMDEqYBlR4eDas59YyI=
